# Generated by Django 4.0.2 on 2022-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfType', models.FileField(upload_to='pdfs')),
                ('language', models.CharField(choices=[('English', 'English'), ('German', 'German'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TextForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textType', models.TextField(max_length=5000, null=True)),
                ('voices', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VideoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoType', models.FileField(upload_to='videos')),
                ('audioType', models.FileField(upload_to='audios')),
            ],
        ),
    ]
